# Generated by Django 6.0.1 on 2026-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_and_catalogue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_ingot_original',
            field=models.BooleanField(default=False, help_text='Designates whether this category belongs to the INGOT Originals collection.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_ingot_original',
            field=models.BooleanField(default=False, help_text='Designates whether this product belongs to the INGOT Originals collection.', verbose_name='INGOT Original'),
        ),
    ]
