# Generated by Django 6.0.1 on 2026-09-27 01:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_is_ingot_original_product_is_ingot_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('tagline', models.CharField(blank=True, help_text='Eyebrow badge text e.g. NEXT-GEN APPAREL', max_length=100)),
                ('link_url', models.CharField(default='/shop/', help_text='Destination URL for CTA', max_length=255)),
                ('button_text', models.CharField(default='Shop Collection', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Slide display order (lowest first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hero banner',
                'verbose_name_plural': 'hero banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Compare-at / MRP price for strikethrough & 'you save' calculation", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lowest first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary thumbnail / hero image')),
                ('alt_text', models.CharField(help_text='Required descriptive alt text for accessibility', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='e.g. S, M, L, XL, XXL, or Free Size', max_length=32)),
                ('color_name', models.CharField(blank=True, help_text='e.g. Stealth Black, Cyan Accent, Heather Grey', max_length=64)),
                ('color_hex', models.CharField(blank=True, default='#111111', help_text='Hex code e.g. #00F0FF for color swatch rendering', max_length=16)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available inventory for this variant')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional custom price for this variant. If left blank, base product price is used.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sku', models.CharField(blank=True, help_text='Optional unique SKU identifier', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['size', 'color_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('chart_data', models.JSONField(blank=True, default=dict, help_text='Structured JSON table with headers, cm measurements, and inch measurements')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_charts', to='products.category')),
            ],
            options={
                'verbose_name': 'size chart',
                'verbose_name_plural': 'size charts',
                'ordering': ['name'],
            },
        ),
    ]
